---
- name: Set timezone
  community.general.timezone:
    name: "{{ time_timezone }}"

- name: Ensure chrony packages are installed
  ansible.builtin.package:
    name: chrony
    state: present

- name: Generate chrony.conf file
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ __time_chrony_conf[ansible_facts['os_family']] }}"
    mode: '0644'
  notify: Restart chrony

- name: Start chrony
  ansible.builtin.systemd:
    name: "{{ __time_chrony_service[ansible_facts['os_family']] }}"
    state: started
    enabled: true
