---
- name: Enable Cgroups limits on login nodes
  become: yes

  tasks:
    # Systemd 240 will not need symlinks as the user- will be default for everyone
    - name: Create base directory
      file:
         path: /etc/systemd/system/user-.slice.d
         state: directory

    - name: Copy default limit drop-in
      copy:
        src: ../files/login-limits.conf
        dest: /etc/systemd/system/user-.slice.d/limits.conf
        owner: root
        group: root
        mode: 644
