- name: Check if cgroup memory in kernel
  shell: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub | grep -c "cgroup_enable=memory"
  register: cgroug_memory
  ignore_errors: true

- name: Enable cgroup memory
  lineinfile: dest="/etc/default/grub" regexp='GRUB_CMDLINE_LINUX_DEFAULT="(.*)"' line='GRUB_CMDLINE_LINUX_DEFAULT="\1 cgroup_enable=memory"' backrefs=yes
  when: cgroug_memory.stdout == "0"

- name: update-grub
  shell: update-grub2
  when: cgroug_memory.stdout == "0"

- name: Check if cgroup v2 in kernel
  shell: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub | grep -c "systemd.unified_cgroup_hierarchy"
  register: cgroup_v2
  ignore_errors: true

- name: Enable cgroup memory
  lineinfile: dest="/etc/default/grub" regexp='GRUB_CMDLINE_LINUX_DEFAULT="(.*)"' line='GRUB_CMDLINE_LINUX_DEFAULT="\1 systemd.unified_cgroup_hierarchy"' backrefs=yes
  when: cgroup_v2.stdout == "0"

- name: update-grub
  shell: update-grub2
  when: cgroup_v2.stdout == "0"

# Systemd 240 will not need symlinks as the user- will be default for everyone
- name: Create base directory
  file:
     path: /etc/systemd/system/user-.slice.d
     state: directory

- name: Copy default limit drop-in
  copy:
    src: ../files/login-limits.conf
    dest: /etc/systemd/system/user-.slice.d/limits.conf
    owner: root
    group: root
    mode: 644
