---

- name: Check if cgroup memory in kernel
  shell: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub | grep -c "cgroup_enable=memory"
  register: cgroup_memory
  ignore_errors: true

- name: Enable cgroup memory
  lineinfile: dest="/etc/default/grub" regexp='GRUB_CMDLINE_LINUX_DEFAULT="(.*)"' line='GRUB_CMDLINE_LINUX_DEFAULT="\1 cgroup_enable=memory"' backrefs=yes
  when: cgroup_memory.stdout == "0"

- name: update-grub
  shell: update-grub2
  when: cgroup_memory.stdout == "0"

- name: Check if cgroup v2 in kernel
  shell: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub | grep -c "systemd.unified_cgroup_hierarchy"
  register: cgroup_v2
  ignore_errors: true

- name: Enable cgroup memory
  lineinfile:
    dest: "/etc/default/grub"
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 systemd.unified_cgroup_hierarchy"'
    backrefs: yes
  when: cgroup_v2.stdout == "0"

- name: update-grub
  shell: update-grub2
  when: cgroup_v2.stdout == "0"

# Systemd 240 will not need symlinks as the user- will be default for everyone
- name: Create base directory
  file:
     path: /etc/systemd/system/user-.slice.d
     state: directory

- name: Copy default limit drop-in
  copy:
    src: login-limits.conf
    dest: /etc/systemd/system/user-.slice.d/limits.conf
    owner: root
    group: root
    mode: 0644

# Get the list of users, run only on 1 host
- name: Get list of users
  getent:
    database: passwd
  delegate_to: 'login-2'
  # when: inventory_hostname == 'login-2'

- name: Create link to limits
  file:
    src: /etc/systemd/system/user-.slice.d
    dest: /etc/systemd/system/user-{{ getent_passwd[item][1] }}.slice.d
    # dest: /etc/systemd/system/user-{{ hostvars['login-2']['getent_passwd'][item][1] }}.slice.d
    state: link
  # when: hostvars['login-2']['getent_passwd'][item][2] == "1500000000"
  when: getent_passwd[item][2] == "1500000000"
  # with_items: "{{ hostvars['login-2']['getent_passwd'].keys() }}"
  with_items: "{{ getent_passwd.keys() }}"

- name: Ensure sshd uses PAM
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^UsePAM.+'
    line: 'UsePAM yes'
  notify: restart sshd
