---

- name: Install google-authenticator Debian
  apt:
    name:
      - fail2ban

- name: Jail defaults
  copy:
    src: fail2ban/defaults-debian.conf
    dest: /etc/fail2ban/jail.d

- name: Jail whitelist
  copy:
    src: fail2ban/defaults-debian.conf
    dest: /etc/fail2ban/jail.d
