---

- name: Install fail2ban service
  apt:
    name:
      - fail2ban

- name: Jail defaults
  template:
    src: fail2ban/defaults-debian.conf.j2
    dest: /etc/fail2ban/jail.d
  notify: restart fail2ban

- name: Jail whitelist
  template:
    src: fail2ban/ignore.conf.j2
    dest: /etc/fail2ban/jail.d
  notify: restart fail2ban

- name: Force fail2ban Restart
  meta: flush_handlers

- name: Check fail2ban is started
  systemd:
    name: fail2ban.service
    state: started
