---

- name: PAM sshd
  template:
    src: pam_sshd.j2
    dest: /etc/pam.d/sshd
    owner: root
    group: root
    mode: 0644

- name: PAM common-auth
  template:
    src: pam_common-auth.j2
    dest: /etc/pam.d/common-auth
    owner: root
    group: root
    mode: 0644

- name: PAM common-auth with PrivacyIDEA
  template:
    src: pam_common-auth-idea.j2
    dest: /etc/pam.d/common-auth-idea
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname == "ci-loginnode"

- name: PAM common-session
  template:
    src: pam_common-session.j2
    dest: /etc/pam.d/common-session
    owner: root
    group: root
    mode: 0644

- name: Banner sshd
  template:
    src: motd_ssh.j2
    dest: "{{ sshd_banner_path }}"
    owner: root
    group: root
    mode: 0644
