---
- name: Install multipath packages
  ansible.builtin.include_tasks:
    file: "install-{{ ansible_facts['os_family'] }}.yml"

- name: Ensure vars existence
  ansible.builtin.assert:
    that:
      - multipath_product is defined
      - multipath_vendor is defined
      - multipath_volumes is defined
    fail_msg: "Missing variables definition in inventory : check multipath_product, multipath_vendor, multipath_volumes"

- name: Configure multipath.conf
  ansible.builtin.template:
    src: "multipath.conf.j2"
    dest: /etc/multipath.conf
    mode: '0644'
    owner: root
    group: root
  notify: Restart multipathd service

- name: Force handlers to run
  ansible.builtin.meta: flush_handlers
