---
- name: Check if cgroup memory in kernel
  ansible.builtin.command: grep -c '^GRUB_CMDLINE_LINUX_DEFAULT=.*cgroup_enable=memory' /etc/default/grub
  changed_when: false
  register: cgroup_memory
  failed_when: "cgroup_memory.rc > 1"

- name: Enable cgroup memory
  ansible.builtin.lineinfile:
    path: "/etc/default/grub"
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 cgroup_enable=memory"'
    backrefs: yes
  when: cgroup_memory.stdout == "0"

- name: Update-grub
  ansible.builtin.command: update-grub2
  when: cgroup_memory.stdout == "0"

- name: Check if cgroup v2 in kernel
  ansible.builtin.command: grep -c '^GRUB_CMDLINE_LINUX_DEFAULT=.*systemd.unified_cgroup_hierarchy' /etc/default/grub
  changed_when: false
  register: cgroup_v2
  failed_when: "cgroup_v2.rc > 1"

- name: Enable cgroup memory
  ansible.builtin.lineinfile:
    dest: "/etc/default/grub"
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 systemd.unified_cgroup_hierarchy"'
    backrefs: yes
  when: cgroup_v2.stdout == "0"

- name: Update-grub
  ansible.builtin.command: update-grub2
  when: cgroup_v2.stdout == "0"

# Use user-.slice.d drop-in (requires systemd version >= 239)
- name: Create base directory /etc/systemd/system/user-.slice.d
  ansible.builtin.file:
    path: /etc/systemd/system/user-.slice.d
    state: directory
    mode: '0755'

- name: Copy default limits drop-in
  ansible.builtin.template:
    src: limits.conf.j2
    dest: /etc/systemd/system/user-.slice.d/limits.conf
    owner: root
    group: root
    mode: '0644'

- name: Create users directories /etc/systemd/system/user-$UID.slice.d
  ansible.builtin.file:
    path: "/etc/systemd/system/user-{{ item }}.slice.d"
    state: directory
    mode: '0755'
  loop: "{{ cgroups_uid_no_limits }}"

- name: Copy users limits drop-in
  vars:
    cgroups_properties: []
  ansible.builtin.template:
    src: limits.conf.j2
    dest: "/etc/systemd/system/user-{{ item }}.slice.d/limits.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ cgroups_uid_no_limits }}"

- name: Check if cgroups v2 is enabled
  ansible.builtin.stat:
    path: /sys/fs/cgroup/user.slice
  register: cgroups_details
