---
- name: Create mila_admins group
  ansible.builtin.group:
    name: mila_admins
    state: present
    gid: "{{ local_users_admins_gid }}"

- name: Allow 'admins' group to have passwordless sudo
  ansible.builtin.copy:
    content: '%mila_admins ALL=(ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/mila_admins
    mode: '0440'

- name: Create Mila admins
  ansible.builtin.user:
    name: "{{ item.name }}-local"
    shell: "{{ item.shell | default('/bin/bash') }}"
    create_home: true
    group: mila_admins
    uid: "{{ item.uid }}"
    password: "{{ item.password }}"
    update_password: always
  loop: "{{ local_users_admins }}"
  loop_control:
    label: "{{ item.name }}"

- name: Remove local keys
  ansible.builtin.file:
    path: "/home/{{ item.name }}-local/.ssh/authorized_keys"
    state: absent
  loop: "{{ local_users_admins }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure authorized_keys cache exists
  ansible.builtin.file:
    path: "{{ local_users_authorized_keys_cache }}"
    state: directory
    owner: nobody
    mode: '0700'

- name: Copy authorized_key template
  ansible.builtin.template:
    src: sshd/mila_authorized_keys.j2
    dest: "{{ local_users_authorized_keys_path }}"
    owner: root
    group: root
    mode: '0755'

# Find and delete removed admins
#
# 1) Build a list of admins defined in the inventory.
# 2) Build a list of admins configured in /etc/passwd.
# 3) Remove any user who is only in the second list.

- name: Get defined list of admins
  ansible.builtin.set_fact:
    _defined_admins: "{{ local_users_admins | map(attribute='name') | list }}"

- name: Slurp /etc/passwd file
  ansible.builtin.slurp:
    src: /etc/passwd
  register: _passwd_file

- name: Get list of configured admins from /etc/passwd
  ansible.builtin.set_fact:
    _configured_admins: '{{ _configured_admins + [item.split("-") | first] }}'
  loop: "{{ (_passwd_file['content'] | b64decode).splitlines() |
     select('match', '^[a-z0-9-.]+:x:[0-9]+:' + local_users_admins_gid | string + ':') |
     list }}"
  no_log: true

- name: Remove gone admins
  ansible.builtin.user:
    name: "{{ item }}-local"
    state: absent
    remove: true
  loop: "{{ _configured_admins | difference(_defined_admins) }}"
