---
- name: Create service account user
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    create_home: true
    group: mila_service_accounts
    uid: "{{ item.uid }}"
    password: "{{ item.password }}"
    update_password: always

- name: Remove local keys
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh/authorized_keys"
    state: absent
