---
# NOTE: Do not break the role yet, give some time to update inventories
- name: Ensure backward compatibility with deprecated variables
  ansible.builtin.import_tasks: backward_compatibility.yml

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - curl
      - sudo

- name: Configure user for automation
  ansible.builtin.import_tasks: automation.yml
  tags:
    - local_automation
    - local_users

- name: Add local admins
  ansible.builtin.import_tasks: admins.yml
  tags:
    - local_admins
    - local_users

- name: Add local operators
  ansible.builtin.import_tasks: operators.yml
  tags:
    - local_operators
    - local_users

- name: Add local service accounts
  ansible.builtin.import_tasks: service_accounts.yml
  tags:
    - local_service_accounts
    - local_users
