---
- name: Create mila_service_accounts group
  ansible.builtin.group:
    name: mila_service_accounts
    state: present
    gid: "{{ local_users_service_accounts_gid }}"

- name: Add service accounts
  ansible.builtin.include_tasks: create_service_accounts.yml
  loop: "{{ local_users_service_accounts }}"
  loop_control:
    label: "{{ item.name }}"
  when: inventory_hostname in item.hosts

# Find and delete removed service_accounts
#
# 1) Build a list of service accounts defined in the inventory.
# 2) Build a list of service accounts configured in /etc/passwd.
# 3) Remove any user who is only in the second list.

- name: Get defined list of service accounts
  ansible.builtin.set_fact:
    _defined_service_accounts: "{{ _defined_service_accounts + [item.name] }}"
  loop: "{{ local_users_service_accounts }}"
  loop_control:
    label: "{{ item.name }}"
  when: inventory_hostname in item.hosts

- name: Slurp /etc/passwd file
  ansible.builtin.slurp:
    src: /etc/passwd
  register: _passwd_file

- name: Get list of configured service accounts from /etc/passwd
  ansible.builtin.set_fact:
    _configured_service_accounts: '{{ _configured_service_accounts + [item.split("-") | first] }}'
  loop: "{{ (_passwd_file['content'] | b64decode).splitlines() |
     select('match', '^[a-z0-9-.]+:x:[0-9]+:' + local_users_service_accounts_gid | string + ':') |
     list }}"
  no_log: true

- name: Remove deleted service accounts
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: true
  loop: "{{ _configured_service_accounts | difference(_defined_service_accounts) }}"

- name: Remove deleted service accounts groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: absent
  loop: "{{ _configured_service_accounts | difference(_defined_service_accounts) }}"

- name: Remove deleted service accounts sudo
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ item }}"
    state: absent
  loop: "{{ _configured_service_accounts | difference(_defined_service_accounts) }}"
