---

- name: cron Projects quota
  cron:
    name: "Projects quota"
    special_time: daily
    job: >
      /cvmfs/config.mila.quebec/etc/rc.d/zfs_quota.sh
      --groups
      cortex_tmp/data/projects
      {{ projects_spacequota }}
      {{ projects_objquota }}
  tags:
    - cron

- name: Send UserDB Groups
  copy:
    src: /tmp/slurmdb/SLURM-group
    dest: /tmp/mila_groups
    owner: root
    group: root
    mode: 0644
  tags:
    - slurm_accounts

- name: Create user project folder
  script: scripts/make_user_folders.sh /tmp/mila_groups /export/data/projects
  args:
    executable: /bin/bash
    removes: /tmp/mila_groups
  register: projects_new_folder
  tags:
    - slurm_accounts

- debug:
    var: projects_new_folder.stdout_lines
  tags:
    - slurm_accounts
