---
- name: Configure /etc/environment
  when: environment_file is defined
  ansible.builtin.copy:
    content: "{{ environment_file }}"
    dest: /etc/environment
    owner: root
    group: root
    mode: '0644'

- name: Source /etc/profile.d/ in bashrc
  ansible.builtin.blockinfile:
    insertafter: "^# System-wide .bashrc.*"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - SOURCE /etc/profile.d/"
    path: /etc/bash.bashrc
    owner: root
    group: root
    mode: '0644'
    state: "{{ environment_source_profiled | bool | ternary('present', 'absent') }}"
    block: "{{ __environment_profiled_bashrc }}"

- name: Configure /etc/profile.d/
  loop: "{{ environment_profile_files }}"
  when: item.state is not defined or item.state == "present"
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "/etc/profile.d/{{ item.name }}"
    owner: root
    group: root
    mode: '0644'

- name: Cleanup /etc/profile.d/
  loop: "{{ environment_profile_files }}"
  when: item.state is defined and item.state == "absent"
  ansible.builtin.file:
    path: "/etc/profile.d/{{ item.name }}"
    state: absent

- name: Import tasks for CC/DRAC environments
  when: environment_cc_env
  ansible.builtin.import_tasks: cc_env.yml

- name: Configure httpproxy module for Lmod
  when: environment_proxy_http is defined
  ansible.builtin.import_tasks: lmod_httpproxy.yml
