---
- name: Install lua Debian
  ansible.builtin.apt:
    name:
      - lua5.1
      - liblua5.1-0
      - liblua5.1-0-dev
      - lua-json
      - lua-filesystem
      - lua-filesystem-dev
      - lua-posix
      - tcl
  when: ansible_facts['os_family'] == 'Debian'

- name: Install lua RedHat
  ansible.builtin.dnf:
    name:
      - lua
      - lua-json
      - lua-filesystem
      - lua-posix
      - tcl
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install other shells
  ansible.builtin.package:
    name:
      - fish
      - zsh
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Force zsh to load profile
  ansible.builtin.copy:
    src: zprofile
    dest: /etc/zsh/
    owner: root
    group: root
    mode: '0755'
