---
- name: Install lua Debian
  ansible.builtin.apt:
    name:
      - lua5.1
      - liblua5.1-0
      - liblua5.1-0-dev
      - lua-json
      - lua-filesystem
      - lua-filesystem-dev
      - lua-posix
      - tcl
  when: ansible_facts['os_family'] == 'Debian'

- name: Install lua RedHat
  ansible.builtin.yum:
    name:
      - lua
      - lua-json
      - lua-filesystem
      - lua-posix
      - tcl
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install other shells
  ansible.builtin.package:
    name:
      - fish
      - zsh
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Force zsh to load profile
  ansible.builtin.copy:
    src: zprofile
    dest: /etc/zsh/
    owner: root
    group: root
    mode: 0755

- name: Mila default profile bash
  ansible.builtin.file:
    src: /cvmfs/config.mila.quebec/etc/profile.d/.z00_Mila.sh
    dest: /etc/profile.d/z99_Mila.sh
    state: link
    force: yes

- name: Mila default profile bourne
  ansible.builtin.file:
    src: /cvmfs/config.mila.quebec/etc/profile.d/.z00_Mila.csh
    dest: /etc/profile.d/z99_Mila.csh
    state: link
    force: yes

# Some packages are already updated with posix.so instead of posix_c.so, in that case skip
- name: Check posix_c exists
  ansible.builtin.stat:
    path: "/usr/lib/{{ ARCH_LIB }}/lua/5.1/posix_c.so"
  register: posix_c_result
  when: ansible_facts['os_family'] == 'Debian'

- name: Create symbolic link for lmod
  ansible.builtin.file:
    src: "/usr/lib/{{ ARCH_LIB }}/lua/5.1/posix_c.so"
    dest: "/usr/lib/{{ ARCH_LIB }}/lua/5.1/posix.so"
    state: link
  when: ansible_facts['os_family'] == 'Debian' and posix_c_result.stat.exists

- name: lmod bash
  ansible.builtin.file:
    src: /cvmfs/ai.mila.quebec/apps/{{ ARCH }}/{{ ansible_facts['os_family'] | lower }}/lmod/lmod/init/profile
    dest: /etc/profile.d/z00_lmod.sh
    state: link
    force: yes
  when: ansible_facts['os_family'] != 'RedHat' or ansible_facts['distribution_major_version'] != "7"

- name: lmod bourne
  ansible.builtin.file:
    src: /cvmfs/ai.mila.quebec/apps/{{ ARCH }}/{{ ansible_facts['os_family'] | lower }}/lmod/lmod/init/cshrc
    dest: /etc/profile.d/z00_lmod.csh
    state: link
    force: yes
  when: ansible_facts['os_family'] != 'RedHat' or ansible_facts['distribution_major_version'] != "7"

- name: lmod fish
  ansible.builtin.file:
    src: /cvmfs/ai.mila.quebec/apps/{{ ARCH }}/{{ ansible_facts['os_family'] | lower }}/lmod/lmod/init/profile.fish
    dest: /etc/fish/conf.d/z00_lmod.fish
    state: link
    force: yes
  when: ansible_facts['os_family'] == 'Debian'

# Trick for rhel7 backward compatibility for old services which will use debian lua5.1
- name: Redhat 7 uses old debian module
  block:

    - name: Install lua RedHat
      ansible.builtin.yum:
        name:
          - http://packages.psychotic.ninja/7/plus/x86_64/RPMS/tcl-8.6.3-1.el7.psychotic.x86_64.rpm

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /usr/lib/lua/
        state: directory
        mode: '0755'

    - name: Symlink for RedHat
      ansible.builtin.file:
        src: /usr/lib64/lua/5.1
        dest: /usr/lib/lua/5.1
        state: link

    - name: lmod bash
      ansible.builtin.file:
        src: /cvmfs/ai.mila.quebec/apps/{{ ARCH }}/debian/lmod/lmod/init/profile
        dest: /etc/profile.d/z00_lmod.sh
        state: link
        force: yes

    - name: lmod bourne
      ansible.builtin.file:
        src: /cvmfs/ai.mila.quebec/apps/{{ ARCH }}/debian/lmod/lmod/init/cshrc
        dest: /etc/profile.d/z00_lmod.csh
        state: link
        force: yes

  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == "7"
    - ansible_architecture == "x86_64"
