---

# Complement Galaxy CVMFS role
- name: Additional options for CernVM-FS config repository
  block:
    - name: Client options
      ansible.builtin.template:
        src: cvmfs_config_repo.local.j2
        dest: /etc/cvmfs/config.d/{{ cvmfs_config_repo.repository.repository }}.local
        owner: root
        group: root
        mode: 0644

    - name: Set env for Variant Symlinks
      ansible.builtin.copy:
        content: |
          ## This file is maintained by Ansible - CHANGES WILL BE OVERWRITTEN
          ARCH={{ ARCH }}
          PROCESSOR_ARCHITECTURE={{ PROCESSOR_ARCHITECTURE }}
          ID={{ ansible_facts['os_family'] | lower }}
        dest: /etc/cvmfs/default.d/01-env.conf
        owner: root
        group: root
        mode: 0444
      notify:
        - reload autofs
  when: cvmfs_config_repo is defined and cvmfs_config_repo_supported
  tags:
    - cvmfs
