---
# Complement Galaxy CVMFS role
- name: Configure CernVM-FS config repository
  block:

    - name: ensure file exists
      copy:
        content: ""
        dest: "/etc/cvmfs/config.d/{{ cvmfs_config_repo.repository.repository }}.conf"
        force: no
        group: root
        owner: root
        mode: 0644

    - name: Additional options for CernVM-FS config repository
      lineinfile:
        dest: "/etc/cvmfs/config.d/{{ cvmfs_config_repo.repository.repository }}.conf"
        regexp: "^{{ item.split('=')[0] }}=.*"
        line: "{{ item }}"
      with_items: "{{ cvmfs_config_repo.repository.client_options }}"

  when: cvmfs_config_repo and cvmfs_config_repo_supported

- name: Ensure repository client options exists
  copy:
    content: ""
    dest: "/etc/cvmfs/repositories.d/{{ item.repository }}/client.conf"
    force: no
    group: root
    owner: root
    mode: 0644
  with_items:
    - "{{ cvmfs_repositories }}"

- name: Set repository client options
  lineinfile:
    dest: "/etc/cvmfs/repositories.d/{{ item.0.repository }}/client.conf"
    regexp: "^{{ item.1.split('=')[0] }}=.*"
    line: "{{ item.1 }}"
  with_subelements:
    - "{{ cvmfs_repositories }}"
    - client_options
