---
# Complement Galaxy CVMFS role
- name: Additional options for CernVM-FS config repository
  ansible.builtin.template:
    src: config.d/config_repo.local.j2
    dest: /etc/cvmfs/config.d/{{ cvmfs_config_repo.repository.repository }}.local
    owner: root
    group: root
    mode: '0644'
  when:
    - cvmfs_config_repo is defined
    - cvmfs_config_repo.repository is defined
    - cvmfs_config_repo_supported
  notify:
    - Reload autofs

- name: Additional configs for CernVM-FS repositories
  ansible.builtin.template:
    src: config.d/repo.local.j2
    dest: "/etc/cvmfs/config.d/{{ item.repository }}.local"
    owner: root
    group: root
    mode: '0444'
  loop: "{{ cvmfs_repositories }}"
  loop_control:
    label: "/etc/cvmfs/config.d/{{ item.repository }}.local"
  when: item.client_configd is defined
  notify:
    - Reload autofs

- name: Ensure /cvmfs /etc/auto.cvmfs --timeout=0 in /etc/auto.master
  ansible.builtin.lineinfile:
    path: /etc/auto.master.d/cvmfs.autofs
    regexp: '^/cvmfs\s+/etc/auto.cvmfs.*'
    line: '/cvmfs /etc/auto.cvmfs --timeout=0'
    owner: root
    group: root
    mode: '0644'
    state: present
    create: true
  notify:
    - Reload autofs
