---
# Remove containers repo for Shifter

- name: Mount /network/containers
  mount:
    src: cortex:/export/containers
    path: /network/containers
    state: absent
    fstype: nfs4
    opts: "ro,{{ nfs_default_opts }}"

- name: Create containers directory
  file:
    path: /network/containers
    state: absent
