---
# ntp_server is deprecated and will be removed in a next release. Use
# time_servers instead which is a list of NTP servers.
# time_servers: ['0.pool.ntp.org','1.pool.ntp.org']
ntp_server: 0.pool.ntp.org

time_timezone: "America/Toronto"
