---
- name: Ensure mountpoints exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: directory
  loop: "{{ mount_volumes }}"
  when: mount_volumes | length > 0

- name: Create File Systems
  community.general.filesystem:
    fstype: "{{ item.fstype | default('ext4') }}"
    dev: "{{ item.source }}"
    state: present
  loop: "{{ mount_volumes }}"
  # Create file system only when source starts with '/dev/'
  when:
    - mount_volumes | length > 0
    - item.source[:5] == '/dev/'

- name: Mount File Systems
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fstype | default('ext4') }}"
    opts: "{{ item.opts | default(omit) }}"
    passno: "{{ item.passno | default(omit) }}"
    state: "{{ item.state | default('mounted') }}"
  loop: "{{ mount_volumes }}"
  when: mount_volumes | length > 0
