---
- name: Disable sssd
  ansible.builtin.systemd:
    name: sssd.service
    state: stopped
    enabled: no

- name: Send Groups
  ansible.builtin.copy:
    src: /tmp/slurmdb/LDAP-group
    dest: /etc/group
    owner: root
    group: root
    mode: 0644

- name: Send Password
  ansible.builtin.copy:
    src: /tmp/slurmdb/LDAP-passwd
    dest: /etc/passwd
    owner: root
    group: root
    mode: 0644

- name: Update sacctmgr
  block:
    - name: Send SLURM Accounts
      ansible.builtin.copy:
        src: /tmp/slurmdb/LDAP-saccounts
        dest: /tmp/LDAP-saccounts
        owner: root
        group: root
        mode: 0644

    - name: Add SLURM Accounts
      ansible.builtin.command: "/opt/slurm/bin/sacctmgr -i load file=/tmp/LDAP-saccounts clean"
      changed_when: true
      register: sacctmgr_output

    - name: Display output of sacctmgr
      ansible.builtin.debug:
        msg: "{{ sacctmgr_output.stdout }}"
  when: inventory_hostname == 'slurm'
