---

- name: disable sssd
  systemd:
    name: sssd.service
    state: stopped
    enabled: no
  ignore_errors: true

- name: Send Groups
  copy:
    src: /tmp/slurmdb/LDAP-group
    dest: /etc/group
    owner: root
    group: root
    mode: 0644

- name: Send Password
  copy:
    src: /tmp/slurmdb/LDAP-passwd
    dest: /etc/passwd
    owner: root
    group: root
    mode: 0644

- name: Update sacctmgr
  block:
    - name: Send SLURM Accounts
      copy:
        src: /tmp/slurmdb/LDAP-saccounts
        dest: /tmp/LDAP-saccounts
        owner: root
        group: root
        mode: 0644

    - name: Add SLURM Accounts
      command: "/opt/slurm/bin/sacctmgr -i load file=/tmp/LDAP-saccounts clean"
      register: sacctmgr_output

    - debug: msg="{{ sacctmgr_output.stdout }}"
  when: inventory_hostname == 'slurm'
