---
- name: cron for Miniscratch cleanup
  cron:
    name: "Miniscratch cleanup"
    special_time: weekly
    disabled: false
    job: >
      find /miniscratch/ -type d \(
      -path /miniscratch/
      -o -path /miniscratch/.keep
      $(printf " -o -path /miniscratch/%s " $(cat /miniscratch/.keep))
      \)
      -prune -o
      -atime +{{ miniscratch_retention_days }}
      -ctime +{{ miniscratch_retention_days }}
      -mtime +{{ miniscratch_retention_days }}
      -exec rm -rf {} \;
  tags:
    - cron
