---
- name: cron for Miniscratch cleanup
  cron:
    name: "Miniscratch cleanup"
    minute: "0"
    hour: "*/2"
    job: |
      find /miniscratch/ -type d \\(
      -path /miniscratch/.keep
      $(printf \" -o -path /miniscratch/%s \" $(cat /miniscratch/.keep))
      \\)
      -prune -o
      -atime +{{ miniscratch_retention_days }}
      -exec echo rm -f {} \\;
  tags:
    - cron
