---
- name: Configure fail2ban for loginnodes
  import_tasks: loginnodes.yml
  when: "'loginnodes' in group_names"

- name: Configure fail2ban for webservers
  import_tasks: webservers.yml
  when: "'webservers' in group_names"
