---
- name: Install fail2ban service
  ansible.builtin.apt:
    name:
      - fail2ban

- name: Copy SSH Filter
  ansible.builtin.copy:
    src: webservers/nginx-ssh-filter.conf
    dest: /etc/fail2ban/filter.d/nginx-ssh-filter.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: Jail defaults
  ansible.builtin.template:
    src: webservers/defaults-debian.conf.j2
    dest: /etc/fail2ban/jail.d/defaults-debian.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: Jail whitelist
  ansible.builtin.template:
    src: webservers/ignore.conf.j2
    dest: /etc/fail2ban/jail.d/ignore.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: Force fail2ban Restart
  ansible.builtin.meta: flush_handlers

- name: Check fail2ban is started
  ansible.builtin.systemd:
    name: fail2ban.service
    state: started
    enabled: true
