---
# Source /etc/profile.d/*.sh in bashrc
__environment_profiled_bashrc: |
  SHELL=/bin/bash
  # Only display echos from profile.d scripts if we are no login shell
  # and interactive - otherwise just process them to set envvars
  for i in /etc/profile.d/*.sh; do
      if [ -r "$i" ]; then
          if [ "$PS1" ]; then
              . "$i"
          else
              . "$i" >/dev/null
          fi
      fi
  done
