---
- name: Install msmtp
  ansible.builtin.package:
    name:
      - msmtp

- name: Generate /etc/msmtprc
  ansible.builtin.template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: msmtp
    mode: 0640

- name: Configure msmtp MTA
  when: msmtp_mta_enabled
  block:
    - name: Install msmtp-mta
      ansible.builtin.package:
        name:
          - msmtp-mta

    - name: Enable msmtpd
      ansible.builtin.systemd:
        name: msmtpd.service
        state: started
        enabled: true
