---
# Define a list of configuration to use for community.general.pamd
#
# e.g., to configure PAM slurm_adopt
# pam_config:
#   - name: sshd
#     type: account
#     control: required
#     module_path: pam_nologin.so
#     new_type: account
#     new_control: sufficient
#     new_module_path: pam_access.so
#     state: after
#   - name: sshd
#     type: account
#     control: sufficient
#     module_path: pam_access.so
#     new_type: account
#     new_control: required
#     new_module_path: pam_slurm_adopt.so
#     state: after
#   - name: common-session
#     type: session
#     control: optional
#     module_path: pam_systemd.so
#     state: absent
#   - name: common-session
#     type: session
#     control: optional
#     module_path: pam_mkhomedir.so
#     state: absent

# Define content of /etc/security/access.conf to use with pam_access.so
#
# e.g.
# pam_access_conf: |
#   + : root : LOCAL
#   + : (wheel) : ALL
#   - : ALL : ALL
