---
- name: Install sssd
  ansible.builtin.package:
    name:
      - sssd
      - sssd-common

- name: Install sssd
  ansible.builtin.package:
    name:
      - sssd-tools
      - libnss-sss
      - libpam-sss
  when: ansible_facts['os_family'] == 'Debian'

- name: Generate /etc/sssd.conf
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart sssd

- name: Restart sssd
  ansible.builtin.systemd:
    name: sssd.service
    state: started
    enabled: yes
